version: '3.8'

services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - localNetwork

  frontclient:
    build:
      context: .
      dockerfile: Dockerfile.frontclient
    ports:
      - "3333:3333"  # Expose the API gateway to the outside world
    networks:
      - localNetwork
      - serversNetwork
    environment:
      CONSUL_ADDRESS: consul:8500
      SERVICE_PORT: 3333
      SERVICE_NAME: api-gateway
      SERVICE_ID: api-gateway1
      SERVICE_WEIGHT: 1.0
      SERVER_URL: http://orion-server-app-1:80
      JWT_SECRET: dsfgbrkjewrw324wdf
      DATABASE_URL: postgresql://user:password@orion-postgres-1:5432/orion
    depends_on:
      - server-app

  server-app:
    build: .
    ports:
       - "80:80"
    networks:
      - localNetwork
      - serversNetwork
    environment:
      DATABASE_URL: postgresql://user:password@orion-postgres-1:5432/orion
      JWT_SECRET: dsfgbrkjewrw324wdf
      MINIO_ENDPOINT: orion-minio-1:9000
      MINIO_ACCESS_KEY: youraccesskey
      MINIO_SECRET_KEY: yoursecretkey
      MINIO_BUCKET: images
      MINIO_USE_SSL: false
      SERVICE_PORT: 80
      SERVICE_NAME: myws
      SERVICE_ID: myws1
      SERVICE_WEIGHT: 1.0

  prometheus:
      image: prom/prometheus
      container_name: prometheus
      ports:
        - "9090:9090"
      volumes:
        - ./prometheus.yml:/etc/prometheus/prometheus.yml
      networks:
        - localNetwork

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: orion
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5555:5432"
    networks:
      - localNetwork
  minio:
    image: minio/minio
    environment:
      MINIO_ROOT_USER: youraccesskey
      MINIO_ROOT_PASSWORD: yoursecretkey
    volumes:
      - minio-data:/data
    command: server /data
    ports:
      - "9000:9000"
    networks:
      - localNetwork


networks:
  localNetwork:
    driver: bridge
    external: false
  serversNetwork:
    driver: bridge
    external: true

volumes:
  minio-data:
  grafana-storage:


#curl -H "Host: go-websocket-server" http://127.0.0.1/metrics

#docker network connect localNetwork orion-server-app-1
#docker network connect serversNetwork orion-server-app-1
#docker network connect serversNetwork orion-frontclient-1
#docker network connect localNetwork orion-frontclient-1
