version: '3.8'

services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - my_network

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - my_network

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: orion
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5555:5432"
  minio:
    image: minio/minio
    environment:
      MINIO_ROOT_USER: youraccesskey
      MINIO_ROOT_PASSWORD: yoursecretkey
    volumes:
      - minio-data:/data
    command: server /data
    ports:
      - "9000:9000"
networks:
  my_network:
    driver: bridge

volumes:
  minio-data:
  grafana-storage:
