version: '3.8'

services:

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: orion
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5555:5432"
  minio:
    image: minio/minio
    environment:
      MINIO_ROOT_USER: youraccesskey
      MINIO_ROOT_PASSWORD: yoursecretkey
    volumes:
      - minio-data:/data
    command: server /data
    ports:
      - "9000:9000"

volumes:
  minio-data: