{
 "title": "Prometheus статистика",
 "tags": [ "prometheus" ],
 "time": { "from": "2025-02-08T05:41:25.379Z", "to": "2025-02-08T07:41:25.379Z" },
 "refresh": "5s",
 "panels": [
  {
   "title": "горутин",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "go_goroutines{job=\"go-app\"}",
     "legendFormat": "горутин"
    }
   ]
  },
  {
   "title": "Scrape Duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "topk(5, max(scrape_duration_seconds) by (job))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Сообщения по ws",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "message_processing_time_seconds_count{job=\"go-app\"}",
     "legendFormat": "{{message}}"
    }
   ]
  },
  {
   "title": "время раоты приложения",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "app_uptime_seconds{job=\"go-app\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Memory Profile",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(process_resident_memory_bytes{job=\"go-app\"})",
     "legendFormat": "p8s process resident memory"
    },
    {
     "expr": "process_virtual_memory_bytes{job=\"prometheus\"}",
     "legendFormat": "virtual memory"
    }
   ]
  },
  {
   "title": "время выполнения",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "avg by(message) (message_processing_time_seconds_bucket{job=\"go-app\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ошибок",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "app_error_total{job=\"go-app\"}",
     "legendFormat": "ошибки"
    }
   ]
  },
  {
   "title": "потоки",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "go_threads{job=\"go-app\"}",
     "legendFormat": "потоки"
    }
   ]
  },
  {
   "title": "алокация",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes_total{job=\"go-app\"}",
     "legendFormat": "алокации"
    }
   ]
  },
  {
   "title": "сеть",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "promhttp_metric_handler_requests_total",
     "legendFormat": "{{code}}"
    }
   ]
  }
 ]
}