scrape_configs:
  - job_name: 'server'
    metrics_path: /service/metrics
    scrape_interval: 5s
    static_configs:
      - targets: ['orion-server-app-1:80']
  - job_name: 'gateway'
    metrics_path: /metrics
    scrape_interval: 5s
    static_configs:
      - targets: ['orion-frontclient-1:3333']

